Task 11
soyvlad/surf-course-v2 pull request #3
Opened 2024-04-11 12:25 UTC by soyvlad

Рад получить комменты и замечания

2024-04-11 13:28 UTC, Evgenia-bit requested changes
Нужно поправить немного :) И прикрепите пожалуйста скрины/видео приложения.

В будущем старайтесь делать так, чтобы другие задания не попадали в ПР

2024-04-11 13:28 UTC, Evgenia-bit commented on task-11/my_business_card/lib/main.dart
> +State<HomePage> createState ()=> _HomePageState();
Форматируйте код :)

2024-04-11 13:28 UTC, Evgenia-bit commented on task-11/my_business_card/lib/pages/hobbies_page.dart
> +abstract class AppColors{
Классы с цветами, текстами, ссылками на ресурсы (путями до картинок) и стилями текста выносите в папку assets в отдельные файлы. И избегайте дублирования классов, храните всё в одном.

2024-04-11 13:28 UTC, Evgenia-bit commented on task-11/my_business_card/lib/pages/hobbies_page.dart
> +        image: AssetImage('assets/viajero.JPG'),
Пути до изображений выносим в отдельный класс подобно цветам.

2024-04-11 13:28 UTC, Evgenia-bit commented on task-11/my_business_card/lib/main.dart
> +    final items = <Widget>[
Выносите такие переменные, которые никогда не изменяются при обновлении виджета, за пределы метода build, чтобы они лишний раз не пересоздавались

2024-04-11 13:28 UTC, Evgenia-bit commented on task-11/my_business_card/lib/main.dart
> +  final screens = [
Если у вас несколько экраном, то используйте навигатор https://docs.flutter.dev/ui/navigation#using-named-routes

2024-04-15 16:42 UTC, danyaao approved these changes

2024-04-15 16:42 UTC, danyaao commented on task-11/my_business_card/lib/assets/app_colors.dart
> +}
На будущее, если речь о классах вроде цветов, строк и т.м., то будет неплохо работать логика один файл - один класс. И немного неудачное название, AppBackCard звучит так, будто это виджет, в конец можно добавить Decoration и станет гораздо понятнее

2024-07-09 20:31 UTC, merged